{
 "title": "Complete 3",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interface",
    "query": "SELECT DISTINCT if_name FROM if_traffic ORDER BY if_name"
   },
   { "name": "selected_time", "label": "selected_time" },
   { "name": "ip_address", "label": "ip_address" },
   { "name": "log_num", "label": "log number", "query": "50" },
   {
    "name": "severity",
    "label": "severity",
    "query": "SELECT severity\nFROM severity_level\nORDER BY level DESC;"
   },
   { "name": "time_interval", "query": "9 hours" },
   { "name": "gap", "query": "2 second" },
   { "name": "Dashboard_name", "query": "complete-3" },
   { "name": "uid", "query": "edtddb9rrqww0e" }
  ]
 },
 "panels": [
  { "title": "interface traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "with sub1 AS (\r\n\tSELECT\r\n\t\tDISTINCT if_name,\r\n\t\tin_packet AS total_in_traffic,\r\n\t\tout_packet AS total_out_traffic,\r\n\t\tin_error_packet AS total_in_error_traffic,\r\n\t\tout_error_packet AS total_out_error_traffic,\r\n\t\tarrival_time\r\n\tFROM\r\n\t\ttb_if_traffic_hist \r\n), sub2 AS (\r\n\tSELECT\r\n\t\tif_name,\r\n\t\ttotal_in_traffic,\r\n\t\ttotal_out_traffic,\r\n\t\ttotal_in_error_traffic,\r\n\t\ttotal_out_error_traffic,\r\n\t\tLAG(total_in_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_traffic,\r\n    LAG(total_out_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_traffic,\r\n    LAG(total_in_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_error_traffic,\r\n    LAG(total_out_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_error_traffic,\r\n   \tarrival_time\r\n   FROM\r\n   \tsub1\r\n   ORDER by\r\n   \tarrival_time\r\n), sub3 AS (\r\n\tSELECT\r\n\t\tif_name,\r\n\t\tCASE \r\n   \t\tWHEN total_in_traffic - prev_in_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_in_traffic - prev_in_traffic < 0 THEN 2^32 - prev_in_traffic + total_in_traffic\r\n   \t\tELSE total_in_traffic - prev_in_traffic\r\n   \tEND AS diff_in_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_traffic - prev_out_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_out_traffic - prev_out_traffic < 0 THEN 2^32 - prev_out_traffic + total_out_traffic\r\n   \t\tELSE total_out_traffic - prev_out_traffic\r\n   \tEND AS diff_out_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_in_error_traffic - prev_in_error_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_in_error_traffic - prev_in_error_traffic < 0 THEN 2^32 - prev_in_error_traffic + total_in_error_traffic\r\n   \t\tELSE total_in_error_traffic - prev_in_error_traffic\r\n   \tEND AS diff_in_error_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_error_traffic - prev_out_error_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_out_error_traffic - prev_out_error_traffic < 0 THEN 2^32 - prev_out_error_traffic + total_out_error_traffic\r\n   \t\tELSE total_out_error_traffic - prev_out_error_traffic\r\n   \tEND AS diff_out_error_traffic,\r\n    arrival_time\r\n   FROM\r\n\t\tsub2\r\n)\r\nSELECT\r\n  diff_in_traffic AS in_traffic, diff_out_traffic AS out_traffic, diff_in_traffic + diff_out_traffic AS total_traffic,\r\n  (arrival_time - INTERVAL '$time_interval') AS time\r\nFROM\r\n  sub3\r\nWHERE\r\n  if_name = '$interface'\r\nORDER BY\r\n  arrival_time DESC;\r\n\r\n-- with sub1 AS (\r\n-- \tSELECT\r\n-- \t\tDISTINCT if_name,\r\n-- \t\tin_packet,\r\n-- \t\tout_packet,\r\n-- \t\tin_error_packet,\r\n-- \t\tout_error_packet,\r\n-- \t\tarrival_time\r\n-- \tFROM\r\n-- \t\tif_traffic\r\n-- ), sub2 AS (\r\n-- \tSELECT\r\n-- \t\tif_name,\r\n-- \t\tSUM(in_packet) AS total_in_traffic,\r\n-- \t\tSUM(out_packet) AS total_out_traffic,\r\n-- \t\tSUM(in_error_packet) AS total_in_error_traffic,\r\n-- \t\tSUM(out_error_packet) AS total_out_error_traffic,\r\n-- \t\tarrival_time\r\n-- \tFROM\r\n-- \t\tsub1\r\n-- \tGROUP BY\r\n-- \t\tif_name, arrival_time\r\n-- ), sub3 AS (\r\n-- \tSELECT\r\n-- \t\tif_name,\r\n-- \t\ttotal_in_traffic,\r\n-- \t\ttotal_out_traffic,\r\n-- \t\ttotal_in_error_traffic,\r\n-- \t\ttotal_out_error_traffic,\r\n-- \t\tLAG(total_in_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_traffic,\r\n--     LAG(total_out_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_traffic,\r\n--     LAG(total_in_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_error_traffic,\r\n--     LAG(total_out_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_error_traffic,\r\n--    \tarrival_time\r\n--    FROM\r\n--    \tsub2\r\n--    ORDER by\r\n--    \tarrival_time\r\n-- ), sub4 AS (\r\n-- \tSELECT\r\n-- \t\tif_name,\r\n-- \t\tCASE \r\n--    \t\tWHEN total_in_traffic - prev_in_traffic IS NULL THEN 0\r\n-- \t\t\tWHEN total_in_traffic - prev_in_traffic <= 0 THEN total_in_traffic\r\n--    \t\tELSE total_in_traffic - prev_in_traffic\r\n--    \tEND AS diff_in_traffic,\r\n-- \t\tCASE \r\n--    \t\tWHEN total_out_traffic - prev_out_traffic IS NULL THEN 0\r\n-- \t\t\tWHEN total_out_traffic - prev_out_traffic <= 0 THEN total_out_traffic\r\n--    \t\tELSE total_out_traffic - prev_out_traffic\r\n--    \tEND AS diff_out_traffic,\r\n-- \t\tCASE \r\n--    \t\tWHEN total_in_error_traffic - prev_in_error_traffic IS NULL THEN 0\r\n-- \t\t\tWHEN total_in_error_traffic - prev_in_error_traffic <= 0 THEN total_in_error_traffic\r\n--    \t\tELSE total_in_error_traffic - prev_in_error_traffic\r\n--    \tEND AS diff_in_error_traffic,\r\n-- \t\tCASE \r\n--    \t\tWHEN total_out_error_traffic - prev_out_error_traffic IS NULL THEN 0\r\n-- \t\t\tWHEN total_out_error_traffic - prev_out_error_traffic <= 0 THEN total_out_error_traffic\r\n--    \t\tELSE total_out_error_traffic - prev_out_error_traffic\r\n--    \tEND AS diff_out_error_traffic,\r\n--     arrival_time\r\n--    FROM\r\n-- \t\tsub3\r\n-- )\r\n-- SELECT\r\n--   diff_in_traffic, diff_out_traffic, diff_in_traffic + diff_out_traffic AS diff_total_traffic,\r\n--   (arrival_time - INTERVAL '$time_interval') AS time\r\n-- FROM\r\n--   sub4\r\n-- WHERE\r\n--   if_name = '$interface'\r\n-- ORDER BY\r\n--   arrival_time DESC;"
    }
   ]
  },
  {
   "title": "error traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "with sub1 AS (\r\n\tSELECT\r\n\t\tDISTINCT if_name,\r\n\t\tin_packet AS total_in_traffic,\r\n\t\tout_packet AS total_out_traffic,\r\n\t\tin_error_packet AS total_in_error_traffic,\r\n\t\tout_error_packet AS total_out_error_traffic,\r\n\t\tarrival_time\r\n\tFROM\r\n\t\ttb_if_traffic_hist \r\n), sub2 AS (\r\n\tSELECT\r\n\t\tif_name,\r\n\t\ttotal_in_traffic,\r\n\t\ttotal_out_traffic,\r\n\t\ttotal_in_error_traffic,\r\n\t\ttotal_out_error_traffic,\r\n\t\tLAG(total_in_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_traffic,\r\n    LAG(total_out_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_traffic,\r\n    LAG(total_in_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_error_traffic,\r\n    LAG(total_out_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_error_traffic,\r\n   \tarrival_time\r\n   FROM\r\n   \tsub1\r\n   ORDER by\r\n   \tarrival_time\r\n), sub3 AS (\r\n\tSELECT\r\n\t\tif_name,\r\n\t\tCASE \r\n   \t\tWHEN total_in_traffic - prev_in_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_in_traffic - prev_in_traffic < 0 THEN 2^32 - prev_in_traffic + total_in_traffic\r\n   \t\tELSE total_in_traffic - prev_in_traffic\r\n   \tEND AS diff_in_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_traffic - prev_out_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_out_traffic - prev_out_traffic < 0 THEN 2^32 - prev_out_traffic + total_out_traffic\r\n   \t\tELSE total_out_traffic - prev_out_traffic\r\n   \tEND AS diff_out_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_in_error_traffic - prev_in_error_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_in_error_traffic - prev_in_error_traffic < 0 THEN 2^32 - prev_in_error_traffic + total_in_error_traffic\r\n   \t\tELSE total_in_error_traffic - prev_in_error_traffic\r\n   \tEND AS diff_in_error_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_error_traffic - prev_out_error_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_out_error_traffic - prev_out_error_traffic < 0 THEN 2^32 - prev_out_error_traffic + total_out_error_traffic\r\n   \t\tELSE total_out_error_traffic - prev_out_error_traffic\r\n   \tEND AS diff_out_error_traffic,\r\n    arrival_time\r\n   FROM\r\n\t\tsub2\r\n)\r\nSELECT\r\n  diff_in_error_traffic AS in_error_traffic, diff_out_error_traffic AS out_error_traffic, diff_in_error_traffic + diff_out_error_traffic AS total_error_traffic,\r\n  (arrival_time - INTERVAL '$time_interval') AS time\r\nFROM\r\n  sub3\r\nWHERE\r\n  if_name = '$interface'\r\nORDER BY\r\n  arrival_time DESC;\r\n\r\n-- SELECT\r\n--   COALESCE(\r\n--     in_error_packet - LAG(in_error_packet) OVER (\r\n--       PARTITION BY if_name\r\n--       ORDER BY\r\n--         arrival_time\r\n--     ),\r\n--     0\r\n--   ) AS in_error_traffic,\r\n--   COALESCE(\r\n--     out_error_packet - LAG(out_error_packet) OVER (\r\n--       PARTITION BY if_name\r\n--       ORDER BY\r\n--         arrival_time\r\n--     ),\r\n--     0\r\n--   ) AS out_error_traffic,\r\n--   (\r\n--     COALESCE(\r\n--       in_error_packet - LAG(in_error_packet) OVER (\r\n--         PARTITION BY if_name\r\n--         ORDER BY\r\n--           arrival_time\r\n--       ),\r\n--       0\r\n--     ) + COALESCE(\r\n--       out_error_packet - LAG(out_error_packet) OVER (\r\n--         PARTITION BY if_name\r\n--         ORDER BY\r\n--           arrival_time\r\n--       ),\r\n--       0\r\n--     )\r\n--   ) AS total_error_traffic,\r\n--   (arrival_time - INTERVAL '$time_interval') AS time\r\n-- FROM\r\n--   (\r\n--     SELECT\r\n--       DISTINCT if_name,\r\n--       in_packet,\r\n--       out_packet,\r\n--       in_error_packet,\r\n--       out_error_packet,\r\n--       arrival_time\r\n--     FROM\r\n--       if_traffic\r\n--   ) AS sub\r\n-- WHERE\r\n--   if_name = '$interface'\r\n-- ORDER BY\r\n--   arrival_time DESC;\r\n\r\n\r\n-- SELECT\r\n--   (in_error_packet + out_error_packet) AS total_error_traffic,\r\n--   out_error_packet AS out_error_traffic,\r\n--   in_error_packet AS in_error_traffic,\r\n--   (arrival_time - INTERVAL '$time_interval') AS time\r\n-- FROM\r\n--   if_traffic\r\n-- WHERE\r\n--   if_name = '$interface'\r\n-- ORDER BY\r\n--   time DESC;"
    }
   ]
  },
  { "title": "interface information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "AP traffic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sub1 AS (\r\n\tSELECT\r\n\t\tDISTINCT if_name,\r\n\t\tin_packet AS total_in_traffic,\r\n\t\tout_packet AS total_out_traffic,\r\n\t\tin_error_packet AS total_in_error_traffic,\r\n\t\tout_error_packet AS total_out_error_traffic,\r\n\t\tarrival_time\r\n\tFROM\r\n\t\ttb_if_traffic_hist \r\n), sub2 AS (\r\n\tSELECT\r\n    \tif_name,\r\n\t    total_in_traffic,\r\n    \ttotal_out_traffic,\r\n        total_in_error_traffic,\r\n\t    total_out_error_traffic,\r\n    \tLAG(total_in_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_traffic,\r\n        LAG(total_out_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_traffic,\r\n        LAG(total_in_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_error_traffic,\r\n        LAG(total_out_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_error_traffic,\r\n   \t    arrival_time\r\n    FROM\r\n        sub1\r\n    ORDER by\r\n   \t    arrival_time\r\n), sub3 AS (\r\n\tSELECT\r\n\t\tif_name,\r\n\t\tCASE \r\n   \t\tWHEN total_in_traffic - prev_in_traffic IS NULL THEN 0\r\n\t\tWHEN total_in_traffic - prev_in_traffic < 0 THEN 2^32 - prev_in_traffic + total_in_traffic\r\n   \t\tELSE total_in_traffic - prev_in_traffic\r\n   \tEND AS diff_in_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_traffic - prev_out_traffic IS NULL THEN 0\r\n\t\tWHEN total_out_traffic - prev_out_traffic < 0 THEN 2^32 - prev_out_traffic + total_out_traffic\r\n   \t\tELSE total_out_traffic - prev_out_traffic\r\n   \tEND AS diff_out_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_in_error_traffic - prev_in_error_traffic IS NULL THEN 0\r\n\t\tWHEN total_in_error_traffic - prev_in_error_traffic < 0 THEN 2^32 - prev_in_error_traffic + total_in_error_traffic\r\n   \t\tELSE total_in_error_traffic - prev_in_error_traffic\r\n   \tEND AS diff_in_error_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_error_traffic - prev_out_error_traffic IS NULL THEN 0\r\n\t\tWHEN total_out_error_traffic - prev_out_error_traffic < 0 THEN 2^32 - prev_out_error_traffic + total_out_error_traffic\r\n   \t\tELSE total_out_error_traffic - prev_out_error_traffic\r\n   \tEND AS diff_out_error_traffic,\r\n    arrival_time\r\n    FROM\r\n\t\tsub2\r\n)\r\nSELECT\r\n    SUM(diff_in_traffic) + SUM(diff_out_traffic) AS diff_total_traffic\r\nFROM\r\n    sub3\r\nGROUP BY \r\n    arrival_time\r\nHAVING\r\n    arrival_time BETWEEN \r\n    (\r\n        COALESCE(\r\n        NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n        (SELECT MAX(arrival_time) FROM tb_if_traffic_hist)\r\n        ) - INTERVAL '${gap}'\r\n    )\r\n    AND \r\n    (\r\n        COALESCE(\r\n        NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n        (SELECT MAX(arrival_time) FROM tb_if_traffic_hist)\r\n        ) + INTERVAL '${gap}'\r\n    ) \r\n\r\n-- WITH sub1 AS (\r\n--     SELECT \r\n--         DISTINCT if_name,\r\n--         in_packet,\r\n--         out_packet,\r\n--         in_error_packet,\r\n--         out_error_packet,\r\n--         arrival_time\r\n--     FROM\r\n--         if_traffic\r\n-- ),\r\n-- sub2 AS (\r\n--     SELECT\r\n--         SUM(in_packet) AS total_in_traffic,\r\n--         SUM(out_packet) AS total_out_traffic,\r\n--         SUM(in_error_packet) AS total_in_error_traffic,\r\n--         SUM(out_error_packet) AS total_out_error_traffic,\r\n--         arrival_time\r\n--     FROM\r\n--         sub1\r\n--     GROUP BY\r\n--         arrival_time\r\n-- ),\r\n-- sub3 AS (\r\n--     SELECT\r\n--         total_in_traffic,\r\n--         total_out_traffic,\r\n--         total_in_error_traffic,\r\n--         total_out_error_traffic,\r\n--         LAG(total_in_traffic) OVER (ORDER BY arrival_time) AS prev_in_traffic,\r\n--         LAG(total_out_traffic) OVER (ORDER BY arrival_time) AS prev_out_traffic,\r\n--         LAG(total_in_error_traffic) OVER (ORDER BY arrival_time) AS prev_in_error_traffic,\r\n--         LAG(total_out_error_traffic) OVER (ORDER BY arrival_time) AS prev_out_error_traffic,\r\n--         arrival_time\r\n--     FROM\r\n--         sub2\r\n-- ),\r\n-- sub4 AS (\r\n--     SELECT\r\n--         CASE \r\n--             WHEN total_in_traffic - prev_in_traffic IS NULL THEN 0\r\n--             WHEN total_in_traffic - prev_in_traffic < 0 THEN total_in_traffic\r\n--             ELSE total_in_traffic - prev_in_traffic\r\n--         END AS diff_in_traffic,\r\n--         CASE \r\n--             WHEN total_out_traffic - prev_out_traffic IS NULL THEN 0\r\n--             WHEN total_out_traffic - prev_out_traffic < 0 THEN total_out_traffic\r\n--             ELSE total_out_traffic - prev_out_traffic\r\n--         END AS diff_out_traffic,\r\n--         CASE \r\n--             WHEN total_in_error_traffic - prev_in_error_traffic IS NULL THEN 0\r\n--             WHEN total_in_error_traffic - prev_in_error_traffic < 0 THEN total_in_error_traffic\r\n--             ELSE total_in_error_traffic - prev_in_error_traffic\r\n--         END AS diff_in_error_traffic,\r\n--             CASE \r\n--             WHEN total_out_error_traffic - prev_out_error_traffic IS NULL THEN 0\r\n--             WHEN total_out_error_traffic - prev_out_error_traffic < 0 THEN total_out_error_traffic\r\n--             ELSE total_out_error_traffic - prev_out_error_traffic\r\n--         END AS diff_out_error_traffic,\r\n--         arrival_time\r\n--     FROM\r\n--         sub3\r\n-- )\r\n-- SELECT\r\n--     diff_in_traffic + diff_out_traffic AS diff_total_traffic\r\n-- FROM\r\n--     sub4\r\n-- WHERE\r\n--     arrival_time BETWEEN \r\n--     (\r\n--         COALESCE(\r\n--         NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n--         (SELECT MAX(arrival_time) FROM if_traffic)\r\n--         ) - INTERVAL '${gap}'\r\n--     )\r\n--     AND \r\n--     (\r\n--         COALESCE(\r\n--         NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n--         (SELECT MAX(arrival_time) FROM if_traffic)\r\n--         ) + INTERVAL '${gap}'\r\n--     ) \r\n\r\n-- WITH sub1 AS (\r\n--     SELECT DISTINCT\r\n--         if_name,\r\n--         in_packet,\r\n--         out_packet,\r\n--         in_error_packet,\r\n--         out_error_packet,\r\n--         arrival_time\r\n--     FROM\r\n--         if_traffic\r\n-- ),\r\n-- sub2 AS (\r\n--     SELECT\r\n--         SUM(in_packet) AS total_in_traffic,\r\n--         SUM(out_packet) AS total_out_traffic,\r\n--         (SUM(in_packet) + SUM(out_packet)) AS total_traffic,\r\n--         SUM(in_error_packet) AS total_in_error_traffic,\r\n--         SUM(out_error_packet) AS total_out_error_traffic,\r\n--         (SUM(in_error_packet) + SUM(out_error_packet)) AS total_error_traffic,\r\n--         arrival_time\r\n--     FROM\r\n--         sub1\r\n--     GROUP BY\r\n--         arrival_time\r\n-- ),\r\n-- sub3 AS (\r\n--     SELECT\r\n--         total_in_traffic,\r\n--         total_out_traffic,\r\n--         total_traffic,\r\n--         total_in_error_traffic,\r\n--         total_out_error_traffic,\r\n--         total_error_traffic,\r\n--         arrival_time,\r\n--         LAG(total_in_traffic) OVER (ORDER BY arrival_time) AS prev_in_traffic,\r\n--         LAG(total_out_traffic) OVER (ORDER BY arrival_time) AS prev_out_traffic,\r\n--         LAG(total_traffic) OVER (ORDER BY arrival_time) AS prev_total_traffic,\r\n--         LAG(total_in_error_traffic) OVER (ORDER BY arrival_time) AS prev_in_error_traffic,\r\n--         LAG(total_out_error_traffic) OVER (ORDER BY arrival_time) AS prev_out_error_traffic,\r\n--         LAG(total_error_traffic) OVER (ORDER BY arrival_time) AS prev_total_error_traffic\r\n--     FROM\r\n--         sub2\r\n-- ),\r\n-- sub4 AS (\r\n--     SELECT\r\n--         GREATEST(total_in_traffic - prev_in_traffic, 0) AS diff_in_traffic,\r\n--         GREATEST(total_out_traffic - prev_out_traffic, 0) AS diff_out_traffic,\r\n--         GREATEST(total_traffic - prev_total_traffic, 0) AS diff_total_traffic,\r\n--         GREATEST(total_in_error_traffic - prev_in_error_traffic, 0) AS diff_in_error_traffic,\r\n--         GREATEST(total_out_error_traffic - prev_out_error_traffic, 0) AS diff_out_error_traffic,\r\n--         GREATEST(total_error_traffic - prev_total_error_traffic, 0) AS diff_total_error_traffic,\r\n--         arrival_time\r\n--     FROM\r\n--         sub3\r\n--     WHERE\r\n--         arrival_time BETWEEN \r\n--         (\r\n--             COALESCE(\r\n--             NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n--             (SELECT MAX(arrival_time) FROM if_traffic)\r\n--             ) - INTERVAL '${gap}'\r\n--         )\r\n--         AND \r\n--         (\r\n--             COALESCE(\r\n--             NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n--             (SELECT MAX(arrival_time) FROM if_traffic)\r\n--             ) + INTERVAL '${gap}'\r\n--         ) \r\n-- )\r\n-- SELECT\r\n--     diff_out_traffic\r\n-- FROM\r\n--     sub4\r\n\r\n  \r\n  -- SELECT\r\n  --   (SUM(in_packet) + SUM(out_packet)) AS total_traffic\r\n  -- FROM\r\n  --   (\r\n  --     SELECT\r\n  --       sum(in_packet) AS total_in_traffic, sum(out_packet) AS total_out_traffic, \r\n  --       (sum(in_packet) + sum(out_packet)) AS total_traffic,\r\n  --       sum(in_error_packet) AS total_in_error_traffic, sum(out_error_packet) AS total_out_error_traffic, \r\n  --       (sum(in_error_packet) + sum(out_error_packet)) AS total_error_traffic,\r\n  --       arrival_time\r\n  --     FROM \r\n  --       (\r\n  --         SELECT\r\n  --           DISTINCT if_name, in_packet, out_packet, in_error_packet, out_error_packet, arrival_time\r\n  --         FROM\r\n  --           if_traffic\r\n  --       ) AS sub1\r\n  --     GROUP BY arrival_time\r\n  --   ) AS sub2\r\n  -- WHERE\r\n  --   arrival_time BETWEEN \r\n  --   (\r\n  --     COALESCE(\r\n  --       NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n  --       (SELECT MAX(arrival_time) FROM if_traffic)\r\n  --     ) - INTERVAL '${gap}'\r\n  --   )\r\n  --   AND \r\n  --   (\r\n  --     COALESCE(\r\n  --       NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n  --       (SELECT MAX(arrival_time) FROM if_traffic)\r\n  --     ) + INTERVAL '${gap}'\r\n  --   )"
    }
   ]
  },
  {
   "title": "AP error traffic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sub1 AS (\r\n\tSELECT\r\n\t\tDISTINCT if_name,\r\n\t\tin_packet AS total_in_traffic,\r\n\t\tout_packet AS total_out_traffic,\r\n\t\tin_error_packet AS total_in_error_traffic,\r\n\t\tout_error_packet AS total_out_error_traffic,\r\n\t\tarrival_time\r\n\tFROM\r\n\t\ttb_if_traffic_hist \r\n), sub2 AS (\r\n\tSELECT\r\n    \tif_name,\r\n\t    total_in_traffic,\r\n    \ttotal_out_traffic,\r\n        total_in_error_traffic,\r\n\t    total_out_error_traffic,\r\n    \tLAG(total_in_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_traffic,\r\n        LAG(total_out_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_traffic,\r\n        LAG(total_in_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_in_error_traffic,\r\n        LAG(total_out_error_traffic) OVER (PARTITION BY if_name ORDER BY arrival_time) AS prev_out_error_traffic,\r\n   \t    arrival_time\r\n    FROM\r\n        sub1\r\n    ORDER by\r\n   \t    arrival_time\r\n), sub3 AS (\r\n\tSELECT\r\n\t\tif_name,\r\n\t\tCASE \r\n   \t\tWHEN total_in_traffic - prev_in_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_in_traffic - prev_in_traffic < 0 THEN 2^32 - prev_in_traffic + total_in_traffic\r\n   \t\tELSE total_in_traffic - prev_in_traffic\r\n   \tEND AS diff_in_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_traffic - prev_out_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_out_traffic - prev_out_traffic < 0 THEN 2^32 - prev_out_traffic + total_out_traffic\r\n   \t\tELSE total_out_traffic - prev_out_traffic\r\n   \tEND AS diff_out_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_in_error_traffic - prev_in_error_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_in_error_traffic - prev_in_error_traffic < 0 THEN 2^32 - prev_in_error_traffic + total_in_error_traffic\r\n   \t\tELSE total_in_error_traffic - prev_in_error_traffic\r\n   \tEND AS diff_in_error_traffic,\r\n\t\tCASE \r\n   \t\tWHEN total_out_error_traffic - prev_out_error_traffic IS NULL THEN 0\r\n\t\t\tWHEN total_out_error_traffic - prev_out_error_traffic < 0 THEN 2^32 - prev_out_error_traffic + total_out_error_traffic\r\n   \t\tELSE total_out_error_traffic - prev_out_error_traffic\r\n   \tEND AS diff_out_error_traffic,\r\n    arrival_time\r\n   FROM\r\n\t\tsub2\r\n)\r\nSELECT\r\n    SUM(diff_in_error_traffic) + SUM(diff_out_error_traffic) AS diff_total_error_traffic\r\nFROM\r\n    sub3\r\nGROUP BY \r\n    arrival_time\r\nHAVING\r\n    arrival_time BETWEEN \r\n    (\r\n        COALESCE(\r\n        NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n        (SELECT MAX(arrival_time) FROM tb_if_traffic_hist)\r\n        ) - INTERVAL '${gap}'\r\n    )\r\n    AND \r\n    (\r\n        COALESCE(\r\n        NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n        (SELECT MAX(arrival_time) FROM tb_if_traffic_hist)\r\n        ) + INTERVAL '${gap}'\r\n    ) \r\n\r\n\r\n-- SELECT\r\n--   (SUM(in_error_packet) + SUM(out_error_packet)) AS total_error_traffic\r\n-- FROM\r\n--   (\r\n--     SELECT\r\n--       DISTINCT if_name, in_error_packet, out_error_packet\r\n--     FROM\r\n--       if_traffic\r\n--     WHERE\r\n--       arrival_time BETWEEN \r\n--       (\r\n--         COALESCE(\r\n--           NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n--           (SELECT MAX(arrival_time) FROM if_traffic)\r\n--         ) - INTERVAL '${gap}'\r\n--       )\r\n--       AND \r\n--       (\r\n--         COALESCE(\r\n--           NULLIF('${selected_time}', '')::timestamp + INTERVAL '${time_interval}',\r\n--           (SELECT MAX(arrival_time) FROM if_traffic)\r\n--         ) + INTERVAL '${gap}'\r\n--       )\r\n--   ) AS subquery;"
    }
   ]
  },
  {
   "title": "ip",
   "type": "table",
   "description": "현재 interface로 연결되어 있는 ip list",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ip.ip_address\r\nFROM\r\n  tb_if_ip_mapping_mst ip\r\n  JOIN tb_if_traffic_hist it ON ip.if_name = it.if_name\r\nWHERE\r\n  it.if_name = '$interface'\r\n  AND ip.arrival_time BETWEEN (\r\n    COALESCE(\r\n      (\r\n        NULLIF('${selected_time}', '') :: timestamp + INTERVAL '$time_interval'\r\n      ),\r\n      (\r\n        SELECT\r\n          MAX(arrival_time)\r\n        FROM\r\n          tb_if_traffic_hist\r\n        WHERE\r\n          if_name = '$interface'\r\n      )\r\n    ) - INTERVAL '$gap'\r\n  )\r\n  AND (\r\n    COALESCE(\r\n      (\r\n        NULLIF('${selected_time}', '') :: timestamp + INTERVAL '$time_interval'\r\n      ),\r\n      (\r\n        SELECT\r\n          MAX(arrival_time)\r\n        FROM\r\n          tb_if_traffic_hist\r\n        WHERE\r\n          if_name = '$interface'\r\n      )\r\n    ) + INTERVAL '$gap'\r\n  )\r\n  AND ip.arrival_time BETWEEN it.arrival_time - INTERVAL '$gap'\r\n  AND it.arrival_time + INTERVAL '$gap'\r\nORDER BY\r\n  ip.ip_address;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 15 },
   "options": {
    "content": "<div style=\"font-size: 1.5em; text-align: center; font-weight: bold;\">\r\n        Admin Status\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "options": {
    "content": "<div style=\"font-size: 1.5em; text-align: center; font-weight: bold;\">\nOper Status\n</div>"
   }
  },
  {
   "type": "stat",
   "description": "관리자가 설정한 interface의 상태",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  admin_status\r\nFROM\r\n  tb_if_traffic_hist\r\nWHERE\r\n  if_name = '$interface'\r\n  AND arrival_time BETWEEN (\r\n    COALESCE(\r\n      NULLIF('${selected_time}', '') :: timestamp + INTERVAL '$time_interval',\r\n      (\r\n        SELECT\r\n          MAX(arrival_time)\r\n        FROM\r\n          tb_if_traffic_hist\r\n        WHERE\r\n          if_name = '$interface'\r\n      )\r\n    ) - INTERVAL '$gap'\r\n  )\r\n  AND (\r\n    COALESCE(\r\n      NULLIF('${selected_time}', '') :: timestamp + INTERVAL '$time_interval',\r\n      (\r\n        SELECT\r\n          MAX(arrival_time)\r\n        FROM\r\n          tb_if_traffic_hist\r\n        WHERE\r\n          if_name = '$interface'\r\n      )\r\n    ) + INTERVAL '$gap'\r\n  )"
    }
   ]
  },
  {
   "type": "stat",
   "description": "현재 interface의 상태",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  oper_status\r\nFROM\r\n  tb_if_traffic_hist\r\nWHERE\r\n  if_name = '$interface'\r\n  AND arrival_time BETWEEN (\r\n    COALESCE(\r\n      NULLIF('${selected_time}', '') :: timestamp + INTERVAL '$time_interval',\r\n      (\r\n        SELECT\r\n          MAX(arrival_time)\r\n        FROM\r\n          tb_if_traffic_hist\r\n        WHERE\r\n          if_name = '$interface'\r\n      )\r\n    ) - INTERVAL '$gap'\r\n  )\r\n  AND (\r\n    COALESCE(\r\n      NULLIF('${selected_time}', '') :: timestamp + INTERVAL '$time_interval',\r\n      (\r\n        SELECT\r\n          MAX(arrival_time)\r\n        FROM\r\n          tb_if_traffic_hist\r\n        WHERE\r\n          if_name = '$interface'\r\n      )\r\n    ) + INTERVAL '$gap'\r\n  )"
    }
   ]
  },
  { "title": "log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "connected ip",
   "type": "table",
   "description": "AP에 연결되어 있는 ip",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ip_address\r\nFROM\r\n  tb_ip_status_mst\r\nWHERE\r\n  connection_status = 1;\r\n"
    }
   ]
  },
  {
   "title": "Log Panel ($ip_address)",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  log_time - INTERVAL '$time_interval' AS time,\r\n  host_name, \r\n  process_name, \r\n  severity, \r\n  content\r\nFROM\r\n  tb_syslog_hist \r\nWHERE\r\n  ip_address = '$ip_address' AND \r\n  ('$severity' = 'all' OR severity = '$severity') AND\r\n  (log_time - INTERVAL '$time_interval') BETWEEN $__timeFrom() AND $__timeTo()\r\nLIMIT \r\n  COALESCE(CAST(NULLIF('$log_num', '') AS INTEGER), (SELECT COUNT(*) FROM syslog_table WHERE '$severity' = 'all' OR severity = '$severity'));\r\n"
    }
   ]
  }
 ]
}